config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :banks
  resources :branches
  resources :accounts
  resources :loans
  resources :atms
  resources :managers
  resources :users
  resources :transactions
end

app/models/user.rb
# frozen_string_literal: true

# Description/Explanation of Person class
class User < ApplicationRecord
  belongs_to :branch
  has_many :accounts, dependent: :destroy
  has_many :loans
  validates :name,
            :father_name,
            :mother_name,
            :address,
            :contact_no,
            presence: true
  validates :contact_no,
            length: { is: 10 },
            numericality: { only_integer: true }
  validate :age_vaild

  private

  def age_vaild
    errors.add(:age, 'age should be greater than 0') if age.nil? || age <= 0
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Description/Explanation of Person class
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @user = User.new
    respond_to do |format|
      format.html {}
      format.json { render json: { user: @user }, status: :ok }
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: { user: @user }, status: :created
    else
      render json: { errors: @user.errors }, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html {}
      format.json { render json: { user: @user }, status: :ok }
    end
  rescue ActiveRecord::RecordNotFound => e
    render json: { errors: e.message }, status: :not_found
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    render json: {}, status: :ok
  rescue ActiveRecord::RecordNotFound => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  def index
    @users = User.all
    render json: { users: @users }, status: :ok
  end

  def edit
    @user = User.find(params[:id])
    respond_to do |format|
      format.html {}
      format.json { render json: { user: @user }, status: :ok }
    end
  rescue ActiveRecord::RecordNotFound => e
    render json: { error: e.message }, status: :not_found
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)

      render json: { user: @user }, status: :ok

    else
      render json: @user.errors, status: :unprocessable_entity
    end
  rescue StandardError => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  private

  def user_params
    params.require(:user).permit(:name, :father_name, :mother_name,
                                 :age, :address, :contact_no, :branch_id)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Description/Explanation of Person class
module UsersHelper
end

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset=“UTF-8”>
    <meta lang=“english”>
    <meta title=“bank”>
    <title>Banking System</title>
  </head>
  <body>
    <h1>Edit user</h1>
    <form class="newuser">
        <input class="branchId" id="BranchId" type="text" name="branchId" hidden="true">
        <input class="userId" id="UserId" type="text" name="userId" hidden="true">
        <label class="heading"> Name:</label>
        <input class="data" id="UserName"type="text" name="userName">
        <label class="heading">Father Name:</label>
        <input class="data" id="FatherName" type="text" name="FatherName">
        <label class="heading">Mother Name:</label>
        <input class="data" id="MotherName" type="text" name="MotherName">
        <br>
        <label class="heading">Address:</label>
        <input class="data" id="UserAddress" type="text" name="address">
        <label class="heading">Age:</label>
        <input class="data" id="Age" type="text" name="Age">
        <label class="heading">Contact_no:</label>
        <input class="data" id="ContactNo" type="text" name="contact_no">
        <input class="button submit" type="button" value="Submit">
      </form> 
  </body>
  <script type="text/javascript">
    jQuery(document).ready(function(){
      var pageLoaded = new EditUser.pageLoaded();
    });
  </script>
</html>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<%= link_to 'New user', new_user_path %>
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>father_name</th>
    <th>mother_name</th>
    <th>age</th>
    <th>Address</th>
    <th>contact_no</th>
    <th colspan="3"></th>
  </tr>
  <% @branches.each do |branch| %>
    <tr>
      <td><%= branch.id %></td>
      <td><%= branch.name %></td>
      <td><%= branch.father_name %></td>
      <td><%= branch.mother_name %></td>
      <td><%= branch.age %></td>
      <td><%= branch.address %></td>
      <td><%= branch.contact_no %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New user</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset=“UTF-8”>
    <meta lang=“english”>
    <meta title=“Banking-system”>
    <title>Banking System</title>
  </head>
  <body class="usershow">
    <div id="user">
      <label class="name header"></label><br />
      <lable class="contact_no header"></lable><br />
    </div>
    <div id="accounts">
     
      <h1>Accounts</h1>
      <table class="list">
        <tr>
          <th>Account No</th>
          <th>Account_Type</th>
          <th>Balance</th>
          <th colspan="3"></th>
        </tr>
      </table>
    </div>
    <button class="button new" id="newaccount">Add New account</button>
    <br><br><br>
    <div id="addaccount">
     
      <form class="newaccount">
        <input class="userId" type="text" name="userId" hidden="true">
        <label class="heading">Account no:</label>
        <input class="data" id="AccountNo"type="text" name="accountno">
        <label class="heading">Account Type:</label>
        <select class="data" id="AccountType" type="text" name="accountype">
          <option>current</option>
          <option>saving</option>
        </select>
        <br>
        <label class="heading">Balance:</label>
        <input class="data" id="Balance" type="text" name="Balance">
        <input class="button submit" type="button" value="Submit">
      </form>
      <br><br> 
    </div> 
    <hr>
    
    <div id="loans">
      
      <h1>Loans</h1>
      <table class="list">
        <tr>
          <th>Loan Type</th>
          <th>Amount</th>
          <th>Interest</th>
          <th>Time period</th>
          <th colspan="3"></th>
        </tr>
      </table>
    </div>
    <button class="button new" id="newloan">Add New Loan</button>  
    <br><br><br>
    <div id="addloan">
      
      <form class="newloan">
        <input class="userId" type="text" name="branchId" hidden="true">
        <label class="heading">Loan Type:</label>
        <select class="data" id="LoanType" type="text" name="Loantype">
         <option>Education_Loan</option>
         <option>Home_Loan</option>
         <option>Personal_Loan</option>    
         <option>Business_Loan</option> 
         <option>Car_Loan</option>
        </select>
        <label class="heading">Amount:</label>
        <input class="data" type="text" id="Amount"name="Amount">
        <br>
        <label class="heading">Interest:</label>
        <input class="data" type="text" id="Interest"name="Interest">
        <label class="heading">Time Period:</label>
        <input class="data" type="text" id="TimePeriod"name="TimePeriod">
        <input class="button submit" type="button" value="Submit">
      </form> 
      <br><br>
    </div> 
  </body>
  <script type="text/javascript">
    jQuery(document).ready(function(){
      var pageLoaded = new ShowUser.pageLoaded();
    });
  </script>
</html>