config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :banks
  resources :branches
  resources :accounts
  resources :loans
  resources :atms
  resources :managers
  resources :users
  resources :transactions
end

app/models/manager.rb
# frozen_string_literal: true

# Description/Explanation of Person class
class Manager < ApplicationRecord
  belongs_to :branch
  validates :name, :contact_no, presence: true
  validates :contact_no,
            length: { is: 10 },
            numericality: { only_integer: true }
end

app/controllers/managers_controller.rb
# frozen_string_literal: true

# Description/Explanation of Person class
class ManagersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @manager = Manager.new
    respond_to do |format|
      format.html {}
      format.json { render json: { manager: @manager }, status: :ok }
    end
  end

  def create
    @manager = Manager.new(manager_params)
    if @manager.save
      render json: { manager: @manager }, status: :created
    else
      render json: { errors: @manager.errors }, status: :unprocessable_entity
    end
  end

  def show
    @manager = Manager.find(params[:id])
    respond_to do |format|
      format.html {}
      format.json { render json: { manager: @manager }, status: :ok }
    end
  rescue ActiveRecord::RecordNotFound => e
    render json: { errors: e.message }, status: :not_found
  end

  def destroy
    @manager = Manager.find(params[:id])
    @manager.destroy
    render json: {}, status: :ok
  rescue ActiveRecord::RecordNotFound => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  def index
    @managers = Manager.all
    render json: { managers: @managers }, status: :ok
  end

  def edit
    @manager = Manager.find(params[:id])
    respond_to do |format|
      format.html {}
      format.json { render json: { manager: @manager }, status: :ok }
    end
  rescue ActiveRecord::RecordNotFound => e
    render json: { error: e.message }, status: :not_found
  end

  def update
    @manager = Manager.find(params[:id])
    if @manager.update(manager_params)
      render json: { manager: @manager }, status: :ok
    else
      render json: @manager.errors, status: :unprocessable_entity
    end
  rescue StandardError => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  private

  def manager_params
    params.require(:manager).permit(:name, :contact_no, :branch_id)
  end
end

app/helpers/managers_helper.rb
# frozen_string_literal: true

# Description/Explanation of Person class
module ManagersHelper
end

app/views/managers/index.html.erb
<h1 >Listing Banks</h1>
 <%= link_to 'New bank', new_bank_path %>
<table>
  <tr>
    <th>Name</th>
    <th>contact_no</th>
    <th></th>
  </tr>
 <tr>
  <% @banks.each do |b| %>
  <td><%= b.name %></td>
      <td><%= b.contact_no %></td>
      <td><%= link_to 'Show', bank_path(b) %></td>
       <td><%= link_to 'Edit', edit_bank_path(b) %></td>
       <td><%= link_to 'Destroy', bank_path(b),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  
</table>

app/views/managers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @bank.name %>
</p>
 
<p>
  <strong>Contact_no:</strong>
  <%= @bank.contact_no %>
</p>
<%= render @bank.branches %>
<%= link_to 'Edit', edit_article_path(@bank) %> 
<%= link_to 'Back', articles_path %>